version: '3.7'
services:
    db:
        image: postgres:10.5
        container_name: db
        restart: always
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"

    dbcreator:
        build:
          context: ./dbcreator
          dockerfile: Dockerfile
        container_name: dbcreator
        volumes:
          - ./data/:/data/
        command: python dbcreator.py
        depends_on:
          - db

    server:
        build:
          context: ./api
          dockerfile: Dockerfile
        container_name: server
        ports:
          - "4545:4545"
        command: uvicorn servis3:app --host 0.0.0.0 --port 4545
        depends_on:
          - db

    bot:
        restart: unless-stopped
        build:
          context: ./bot
          dockerfile: Dockerfile
        container_name: bot
        ports:
          - "8000:8000"
        command: python main.py